/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Photos',
      [
        { jewelryID: 1, url: '/img/1_1.jpg' },
        { jewelryID: 1, url: '/img/1_2.jpeg' },
        { jewelryID: 1, url: '/img/1_3.jpeg' },
        { jewelryID: 2, url: '/img/2_1.png' },
        { jewelryID: 3, url: '/img/3_1.jpeg' },
        { jewelryID: 3, url: '/img/3_2.jpeg' },
        { jewelryID: 3, url: '/img/3_3.jpeg' },
        { jewelryID: 4, url: '/img/4_1.jpeg' },
        { jewelryID: 5, url: '/img/5_1.jpeg' },
        { jewelryID: 5, url: '/img/5_2.jpeg' },
        { jewelryID: 5, url: '/img/5_3.jpeg' },
        { jewelryID: 6, url: '/img/6_1.jpeg' },
        { jewelryID: 6, url: '/img/6_2.jpeg' },
        { jewelryID: 7, url: '/img/7_1.jpeg' },
        { jewelryID: 7, url: '/img/7_2.jpeg' },
        { jewelryID: 8, url: '/img/8_1.jpeg' },
        { jewelryID: 8, url: '/img/8_2.jpeg' },
        { jewelryID: 9, url: '/img/9_1.jpeg' },
        { jewelryID: 9, url: '/img/9_2.jpeg' },
        { jewelryID: 10, url: '/img/10_1.jpeg' },
        { jewelryID: 10, url: '/img/10_2.jpeg' },
        { jewelryID: 11, url: '/img/11_1.jpeg' },
        { jewelryID: 11, url: '/img/11_2.jpeg' },
        { jewelryID: 12, url: '/img/12_1.jpeg' },
        { jewelryID: 12, url: '/img/12_2.jpeg' },
        { jewelryID: 12, url: '/img/12_3.jpeg' },
        { jewelryID: 13, url: '/img/13_1.jpeg' },
        { jewelryID: 14, url: '/img/14_1.jpeg' },
        { jewelryID: 14, url: '/img/14_2.jpeg' },
        { jewelryID: 14, url: '/img/14_3.jpeg' },
        { jewelryID: 15, url: '/img/15_1.jpeg' },
        { jewelryID: 15, url: '/img/15_2.jpeg' },
        { jewelryID: 15, url: '/img/15_3.jpeg' },
        { jewelryID: 16, url: '/img/16_1.jpeg' },
        { jewelryID: 16, url: '/img/16_2.jpeg' },
        { jewelryID: 16, url: '/img/16_3.jpeg' },
        { jewelryID: 17, url: '/img/17_1.jpeg' },
        { jewelryID: 17, url: '/img/17_2.jpeg' },
        { jewelryID: 17, url: '/img/17_3.jpeg' },
        { jewelryID: 17, url: '/img/17_4.png' },
        { jewelryID: 18, url: '/img/18_1.jpeg' },
        { jewelryID: 18, url: '/img/18_2.jpeg' },
        { jewelryID: 19, url: '/img/19_1.jpeg' },
        { jewelryID: 19, url: '/img/19_2.jpeg' },
        { jewelryID: 19, url: '/img/19_3.jpeg' },
        { jewelryID: 20, url: '/img/20_1.jpeg' },
        { jewelryID: 20, url: '/img/20_2.jpeg' },
        { jewelryID: 21, url: '/img/21_1.jpeg' },
        { jewelryID: 21, url: '/img/21_2.jpeg' },
        { jewelryID: 21, url: '/img/21_3.png' },
        { jewelryID: 22, url: '/img/22_1.png' },
        { jewelryID: 22, url: '/img/22_2.jpeg' },
        { jewelryID: 23, url: '/img/23_1.png' },
        { jewelryID: 23, url: '/img/23_2.png' },
        { jewelryID: 24, url: '/img/24_1.jpeg' },
        { jewelryID: 24, url: '/img/24_2.jpeg' },
        { jewelryID: 25, url: '/img/25_1.jpeg' },
        { jewelryID: 25, url: '/img/25_2.jpeg' },
        { jewelryID: 26, url: '/img/26_1.jpeg' },
        { jewelryID: 26, url: '/img/26_2.jpeg' },
        { jewelryID: 27, url: '/img/27_1.jpeg' },
        { jewelryID: 27, url: '/img/27_2.jpeg' },
        { jewelryID: 27, url: '/img/27_3.jpeg' },
        { jewelryID: 28, url: '/img/28_1.jpeg' },
        { jewelryID: 28, url: '/img/28_2.jpeg' },
        { jewelryID: 29, url: '/img/29_1.jpeg' },
        { jewelryID: 29, url: '/img/29_2.jpeg' },
        { jewelryID: 30, url: '/img/30_1.jpeg' },
        { jewelryID: 30, url: '/img/30_2.jpeg' },
        { jewelryID: 31, url: '/img/31_1.jpeg' },
        { jewelryID: 31, url: '/img/31_2.jpeg' },
        { jewelryID: 32, url: '/img/32_1.jpeg' },
        { jewelryID: 33, url: '/img/33_1.jpeg' },
        { jewelryID: 33, url: '/img/33_2.jpeg' },
        { jewelryID: 33, url: '/img/33_3.png' },
        { jewelryID: 34, url: '/img/34_1.jpeg' },
        { jewelryID: 35, url: '/img/35_1.png' },
        { jewelryID: 35, url: '/img/35_2.jpeg' },
        { jewelryID: 35, url: '/img/35_3.jpeg' },
        { jewelryID: 36, url: '/img/36_1.jpeg' },
        { jewelryID: 36, url: '/img/36_2.jpeg' },
        { jewelryID: 37, url: '/img/37_1.jpeg' },
        { jewelryID: 37, url: '/img/37_2.jpeg' },
        { jewelryID: 37, url: '/img/37_3.jpeg' },
        { jewelryID: 38, url: '/img/38_1.png' },
        { jewelryID: 38, url: '/img/38_2.png' },
        { jewelryID: 38, url: '/img/38_3.jpeg' },
        { jewelryID: 39, url: '/img/39_1.jpeg' },
        { jewelryID: 39, url: '/img/39_2.png' },
        { jewelryID: 40, url: '/img/40_1.png' },
        { jewelryID: 40, url: '/img/40_2.jpeg' },
        { jewelryID: 40, url: '/img/40_3.jpeg' },
        { jewelryID: 41, url: '/img/41_1.png' },
        { jewelryID: 41, url: '/img/41_2.png' },
        { jewelryID: 42, url: '/img/42_1.jpeg' },
        { jewelryID: 43, url: '/img/43_1.jpeg' },
        { jewelryID: 43, url: '/img/43_2.jpeg' },
        { jewelryID: 44, url: '/img/44_1.png' },
        { jewelryID: 44, url: '/img/44_2.png' },
        { jewelryID: 45, url: '/img/45_1.png' },
        { jewelryID: 45, url: '/img/45_2.jpeg' },
        { jewelryID: 45, url: '/img/45_3.png' },
        { jewelryID: 46, url: '/img/46_1.png' },
        { jewelryID: 46, url: '/img/46_2.jpeg' },
        { jewelryID: 47, url: '/img/47_1.jpeg' },
        { jewelryID: 47, url: '/img/47_2.jpeg' },
        { jewelryID: 48, url: '/img/48_1.jpeg' },
        { jewelryID: 48, url: '/img/48_2.jpeg' },
        { jewelryID: 49, url: '/img/49_1.jpeg' },
        { jewelryID: 49, url: '/img/49_2.jpeg' },
        { jewelryID: 49, url: '/img/49_3.jpeg' },
        { jewelryID: 50, url: '/img/50_1.jpeg' },
        { jewelryID: 50, url: '/img/50_2.jpeg' },
        { jewelryID: 51, url: '/img/51_1.jpeg' },
        { jewelryID: 51, url: '/img/51_2.png' },
        { jewelryID: 52, url: '/img/52_1.jpeg' },
        { jewelryID: 52, url: '/img/52_2.jpeg' },
        { jewelryID: 53, url: '/img/53_1.jpeg' },
        { jewelryID: 53, url: '/img/53_2.jpeg' },
        { jewelryID: 54, url: '/img/54_1.jpeg' },
        { jewelryID: 54, url: '/img/54_2.png' },
        { jewelryID: 55, url: '/img/55_1.png' },
      ].map((el) => ({ ...el, createdAt: new Date(), updatedAt: new Date() })),
      {}
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Photos', null, {});
  },
};
